modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
[[mods]]
modId="ingametips"
version="1.0.3"
displayName="Ingame Tips"
authors="goumo_g"
description='''
Display tip in the game!
'''
[[dependencies.ingametips]]
    modId = "forge"
    mandatory = true
    versionRange = "[46,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.ingametips]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20,1.20.2)"
    ordering = "NONE"
    side = "BOTH"
